import os
import cv2
import pytesseract
import numpy as np
import os
from dotenv import load_dotenv
from flask import Flask, request, jsonify
from nlp_parser import parse_medical_text
from gemini_service import generate_clinical_summary

import pytesseract

pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

# Load environment variables from .env
load_dotenv()

app = Flask(__name__)

# IMPORTANT FOR WINDOWS USERS: 
# If Tesseract is not in your system PATH, you must provide its executable path below.
# Default install path is usually: r'C:\Program Files\Tesseract-OCR\tesseract.exe'
# Uncomment the following line and update the path if necessary:
# pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

@app.route('/ocr', methods=['POST'])
def ocr_endpoint():
    """
    Endpoint: POST /ocr
    Expects to receive an image file via form-data named 'file'.
    Returns structured JSON with the extracted text.
    """
    if 'file' not in request.files:
        return jsonify({"error": "No file part in the request"}), 400
    
    file = request.files['file']
    
    if file.filename == '':
        return jsonify({"error": "No selected file"}), 400

    try:
        # 1. Read the uploaded image dynamically into memory using numpy 
        in_memory_file = file.read()
        nparr = np.frombuffer(in_memory_file, np.uint8)
        
        # 2. Decode the raw Bytes into a valid OpenCV image/matrix
        img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

        if img is None:
            return jsonify({"error": "Invalid image file format"}), 400

        # --- Optional Pre-processing Step ---
        # OpenCV enables converting to grayscale and blurring to increase OCR accuracy.
        # It's highly recommended but we will keep this direct and simple right now:
        # gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
        # 3. Use Tesseract to perform OCR directly on the image mat
        extracted_text = pytesseract.image_to_string(img)

        # 4. Return Output Format
        return jsonify({
            "raw_text": extracted_text.strip()
        }), 200

    except Exception as e:
        return jsonify({"error": f"OCR Processing Error: {str(e)}"}), 500

@app.route('/structure', methods=['POST'])
def structure_endpoint():
    """
    Endpoint: POST /structure
    Expects to receive a JSON payload with 'raw_text'.
    Outputs structured JSON containing diagnosis, medications, and recommended tests.
    """
    data = request.get_json()
    
    # Payload validation check
    if not data or 'raw_text' not in data:
        return jsonify({"error": "Missing 'raw_text' field in JSON payload"}), 400
        
    raw_text = data['raw_text']
    
    try:
        # Run Rule-based NLP parser on string
        structured_data = parse_medical_text(raw_text)
        return jsonify(structured_data), 200
        
    except Exception as e:
        return jsonify({"error": f"NLP Structuring Error: {str(e)}"}), 500

@app.route('/ai-summary', methods=['POST'])
def ai_summary_endpoint():
    """
    Endpoint: POST /ai-summary
    Expects to receive a JSON payload with patient history data.
    Outputs a structured JSON generated by Gemini AI with `summary`, `risks`, and `patterns`.
    """
    data = request.get_json()
    
    if not data:
        return jsonify({"error": "Missing JSON payload for medical history"}), 400
        
    try:
        # Pass JSON straight into the Gemini parser hook
        summary_result = generate_clinical_summary(data)
        return jsonify(summary_result), 200
        
    except ValueError as ve:
         # Missing API key Error
        return jsonify({"error": str(ve)}), 401 
    except Exception as e:
        return jsonify({"error": f"AI Summarization Error: {str(e)}"}), 500

if __name__ == '__main__':
    # We host on port 5001 so it doesn't conflict with the Node.js backend (Port 5000)
    app.run(debug=True, host='0.0.0.0', port=5001)
